version: "3"
services:

  db:
    image: postgres
    container_name: independer-db
    ports:
      - "5450:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: independer-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  app:
    build: ./
    container_name: independer-app
    image: independer-app-img
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

  reverse:
    container_name: independer-reverse
    image: nginx
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 5001:443 # 443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./key.pem:/root/ssl/key.pem:ro
      - ./cert.pem:/root/ssl/cert.pem:ro